In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
import tensorflow as tf
from tensorflow import keras

In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [4]:
df=pd.read_csv("D:\\Saurabh\\Colab Files\\Artificial_Neural_Networks Colab\\Churn_Modelling.csv")

In [5]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
#independent and dependent 
X=df.iloc[:,3:-1]
y=df.iloc[:,-1]
print("X: Independent_Varibale")
print("y: Dependent_Varibale")

X: Independent_Varibale
y: Dependent_Varibale

In [7]:
#shape
print('X_shape:',X.shape)
print('y_shape:',y.shape)

X_shape: (10000, 10)
y_shape: (10000,)

In [14]:
#get dummies
geo =pd.get_dummies(X['Geography'],drop_first=True)
gen =pd.get_dummies(X['Gender'],drop_first=True)

In [15]:
print(geo)
print(gen)

      Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]
      Male
0        0
1        0
2        0
3        0
4        0
...    ...
9995     1
9996     1
9997     0
9998     1
9999     0

[10000 rows x 1 columns]

In [16]:
#concat the geo and gen
X =pd.concat([X,geo,gen],axis=1)

In [18]:
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
0,619,France,Female,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,1,0

In [20]:
#drop Geography and Gender
X.drop(labels=['Geography','Gender'],axis=1,inplace=True)

In [21]:
X.head(3)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0

In [26]:
#scaling 
from sklearn.preprocessing import StandardScaler
Scaler =StandardScaler()
X_scale =Scaler.fit_transform(X)

In [27]:
#train_test_splits
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X_scale,y,test_size=0.3,random_state=11)
print('X_train_shape:',X_train.shape)
print('y_train_shape:',y_train.shape)
print('X_test_shape:',X_test.shape)
print('y_test_shape:',y_test.shape)

X_train_shape: (7000, 11)
y_train_shape: (7000,)
X_test_shape: (3000, 11)
y_test_shape: (3000,)

In [29]:
#creating ANN
classifer = Sequential()

In [40]:
#adding input layers to ANN that is first layers
classifer.add(Dense(units=15,kernel_initializer='he_uniform',activation='relu',input_dim=11))
#2nd_layers
classifer.add(Dense(units=20,kernel_initializer='he_uniform',activation='relu'))
#3rd_layer
classifer.add(Dense(units=25,kernel_initializer='he_uniform',activation='relu'))
#output_layers 
classifer.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))

In [41]:
#summary_classifer
classifer.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 6)                 72
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_3 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 7
_________________________________________________________________
dense_5 (Dense)              (None, 15)                30
_________________________________________________________________
dense_6 (Dense)              (None, 20)                320
_________________________________________________________________
dense_7 (Dense)              (None, 25)                525
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 26
=================================================================
Total params: 1,106
Trainable params: 1,106
Non-trainable params: 0
_________________________________________________________________

In [42]:
#compile the classifier
classifer.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [43]:
model_his=classifer.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=100)

Epoch 1/100
469/469 [==============================] - 4s 4ms/step - loss: 0.5155 - accuracy: 0.7978 - val_loss: 0.3520 - val_accuracy: 0.8542
Epoch 2/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3428 - accuracy: 0.8629 - val_loss: 0.3506 - val_accuracy: 0.8563
Epoch 3/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3552 - accuracy: 0.8570 - val_loss: 0.3540 - val_accuracy: 0.8550
Epoch 4/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3486 - accuracy: 0.8595 - val_loss: 0.3767 - val_accuracy: 0.8498
Epoch 5/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3533 - accuracy: 0.8541 - val_loss: 0.3481 - val_accuracy: 0.8524
Epoch 6/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3319 - accuracy: 0.8705 - val_loss: 0.3502 - val_accuracy: 0.8529
Epoch 7/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3422 - accuracy: 0.8634 - val_loss: 0.3507 - val_accuracy: 0.8533
Epoch 8/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3456 - accuracy: 0.8578 - val_loss: 0.3488 - val_accuracy: 0.8568
Epoch 9/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3519 - accuracy: 0.8527 - val_loss: 0.3492 - val_accuracy: 0.8524
Epoch 10/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3412 - accuracy: 0.8593 - val_loss: 0.3568 - val_accuracy: 0.8503
Epoch 11/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3379 - accuracy: 0.8642 - val_loss: 0.3538 - val_accuracy: 0.8507
Epoch 12/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3452 - accuracy: 0.8610 - val_loss: 0.3476 - val_accuracy: 0.8568
Epoch 13/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3295 - accuracy: 0.8676 - val_loss: 0.3489 - val_accuracy: 0.8537
Epoch 14/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3467 - accuracy: 0.8560 - val_loss: 0.3475 - val_accuracy: 0.8589
Epoch 15/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3482 - accuracy: 0.8586 - val_loss: 0.3527 - val_accuracy: 0.8542
Epoch 16/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3381 - accuracy: 0.8645 - val_loss: 0.3524 - val_accuracy: 0.8520
Epoch 17/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3416 - accuracy: 0.8666 - val_loss: 0.3497 - val_accuracy: 0.8546
Epoch 18/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3400 - accuracy: 0.8583 - val_loss: 0.3476 - val_accuracy: 0.8550
Epoch 19/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3302 - accuracy: 0.8668 - val_loss: 0.3512 - val_accuracy: 0.8490
Epoch 20/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3290 - accuracy: 0.8675 - val_loss: 0.3599 - val_accuracy: 0.8503
Epoch 21/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3376 - accuracy: 0.8618 - val_loss: 0.3522 - val_accuracy: 0.8486
Epoch 22/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3527 - accuracy: 0.8596 - val_loss: 0.3547 - val_accuracy: 0.8542
Epoch 23/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3361 - accuracy: 0.8644 - val_loss: 0.3469 - val_accuracy: 0.8529
Epoch 24/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3415 - accuracy: 0.8610 - val_loss: 0.3521 - val_accuracy: 0.8507
Epoch 25/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3307 - accuracy: 0.8681 - val_loss: 0.3458 - val_accuracy: 0.8542
Epoch 26/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3424 - accuracy: 0.8558 - val_loss: 0.3466 - val_accuracy: 0.8529
Epoch 27/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3421 - accuracy: 0.8639 - val_loss: 0.3497 - val_accuracy: 0.8524
Epoch 28/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3360 - accuracy: 0.8643 - val_loss: 0.3465 - val_accuracy: 0.8546
Epoch 29/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3344 - accuracy: 0.8646 - val_loss: 0.3516 - val_accuracy: 0.8516
Epoch 30/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3397 - accuracy: 0.8620 - val_loss: 0.3480 - val_accuracy: 0.8555
Epoch 31/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3474 - accuracy: 0.8616 - val_loss: 0.3456 - val_accuracy: 0.8550
Epoch 32/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3326 - accuracy: 0.8686 - val_loss: 0.3456 - val_accuracy: 0.8559
Epoch 33/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3284 - accuracy: 0.8753 - val_loss: 0.3470 - val_accuracy: 0.8529
Epoch 34/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3274 - accuracy: 0.8688 - val_loss: 0.3490 - val_accuracy: 0.8503
Epoch 35/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3244 - accuracy: 0.8722 - val_loss: 0.3459 - val_accuracy: 0.8555
Epoch 36/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3300 - accuracy: 0.8684 - val_loss: 0.3450 - val_accuracy: 0.8507
Epoch 37/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3387 - accuracy: 0.8611 - val_loss: 0.3501 - val_accuracy: 0.8529
Epoch 38/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3351 - accuracy: 0.8676 - val_loss: 0.3459 - val_accuracy: 0.8559
Epoch 39/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3359 - accuracy: 0.8602 - val_loss: 0.3503 - val_accuracy: 0.8503
Epoch 40/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3358 - accuracy: 0.8640 - val_loss: 0.3448 - val_accuracy: 0.8537
Epoch 41/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3392 - accuracy: 0.8633 - val_loss: 0.3482 - val_accuracy: 0.8511
Epoch 42/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3260 - accuracy: 0.8717 - val_loss: 0.3513 - val_accuracy: 0.8511
Epoch 43/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3419 - accuracy: 0.8582 - val_loss: 0.3451 - val_accuracy: 0.8546
Epoch 44/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3362 - accuracy: 0.8642 - val_loss: 0.3589 - val_accuracy: 0.8503
Epoch 45/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3482 - accuracy: 0.8582 - val_loss: 0.3450 - val_accuracy: 0.8494
Epoch 46/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3445 - accuracy: 0.8572 - val_loss: 0.3497 - val_accuracy: 0.8507
Epoch 47/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3282 - accuracy: 0.8688 - val_loss: 0.3464 - val_accuracy: 0.8520
Epoch 48/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3253 - accuracy: 0.8710 - val_loss: 0.3667 - val_accuracy: 0.8511
Epoch 49/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3395 - accuracy: 0.8593 - val_loss: 0.3457 - val_accuracy: 0.8529
Epoch 50/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3296 - accuracy: 0.8696 - val_loss: 0.3460 - val_accuracy: 0.8550
Epoch 51/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3398 - accuracy: 0.8627 - val_loss: 0.3462 - val_accuracy: 0.8516
Epoch 52/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3377 - accuracy: 0.8615 - val_loss: 0.3458 - val_accuracy: 0.8550
Epoch 53/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3525 - accuracy: 0.8470 - val_loss: 0.3464 - val_accuracy: 0.8542
Epoch 54/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3292 - accuracy: 0.8699 - val_loss: 0.3469 - val_accuracy: 0.8568
Epoch 55/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3348 - accuracy: 0.8644 - val_loss: 0.3470 - val_accuracy: 0.8516
Epoch 56/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3326 - accuracy: 0.8646 - val_loss: 0.3447 - val_accuracy: 0.8542
Epoch 57/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3248 - accuracy: 0.8712 - val_loss: 0.3461 - val_accuracy: 0.8511
Epoch 58/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3296 - accuracy: 0.8669 - val_loss: 0.3516 - val_accuracy: 0.8507
Epoch 59/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3211 - accuracy: 0.8698 - val_loss: 0.3508 - val_accuracy: 0.8529
Epoch 60/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3234 - accuracy: 0.8718 - val_loss: 0.3445 - val_accuracy: 0.8542
Epoch 61/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3380 - accuracy: 0.8671 - val_loss: 0.3472 - val_accuracy: 0.8503
Epoch 62/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3327 - accuracy: 0.8628 - val_loss: 0.3471 - val_accuracy: 0.8524
Epoch 63/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3165 - accuracy: 0.8707 - val_loss: 0.3456 - val_accuracy: 0.8542
Epoch 64/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3415 - accuracy: 0.8620 - val_loss: 0.3453 - val_accuracy: 0.8529
Epoch 65/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3356 - accuracy: 0.8621 - val_loss: 0.3464 - val_accuracy: 0.8533
Epoch 66/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3315 - accuracy: 0.8657 - val_loss: 0.3451 - val_accuracy: 0.8555
Epoch 67/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3115 - accuracy: 0.8791 - val_loss: 0.3492 - val_accuracy: 0.8503
Epoch 68/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3400 - accuracy: 0.8625 - val_loss: 0.3547 - val_accuracy: 0.8524
Epoch 69/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3384 - accuracy: 0.8630 - val_loss: 0.3465 - val_accuracy: 0.8550
Epoch 70/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3142 - accuracy: 0.8699 - val_loss: 0.3470 - val_accuracy: 0.8529
Epoch 71/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3229 - accuracy: 0.8698 - val_loss: 0.3456 - val_accuracy: 0.8529
Epoch 72/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3369 - accuracy: 0.8620 - val_loss: 0.3477 - val_accuracy: 0.8537
Epoch 73/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3304 - accuracy: 0.8624 - val_loss: 0.3533 - val_accuracy: 0.8507
Epoch 74/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3442 - accuracy: 0.8606 - val_loss: 0.3453 - val_accuracy: 0.8516
Epoch 75/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3280 - accuracy: 0.8662 - val_loss: 0.3540 - val_accuracy: 0.8516
Epoch 76/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3251 - accuracy: 0.8697 - val_loss: 0.3450 - val_accuracy: 0.8546
Epoch 77/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3355 - accuracy: 0.8575 - val_loss: 0.3519 - val_accuracy: 0.8507
Epoch 78/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3343 - accuracy: 0.8660 - val_loss: 0.3467 - val_accuracy: 0.8529
Epoch 79/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3271 - accuracy: 0.8674 - val_loss: 0.3509 - val_accuracy: 0.8524
Epoch 80/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3274 - accuracy: 0.8653 - val_loss: 0.3530 - val_accuracy: 0.8503
Epoch 81/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3209 - accuracy: 0.8745 - val_loss: 0.3467 - val_accuracy: 0.8529
Epoch 82/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3273 - accuracy: 0.8695 - val_loss: 0.3449 - val_accuracy: 0.8550
Epoch 83/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3323 - accuracy: 0.8635 - val_loss: 0.3489 - val_accuracy: 0.8524
Epoch 84/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3322 - accuracy: 0.8689 - val_loss: 0.3472 - val_accuracy: 0.8507
Epoch 85/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3235 - accuracy: 0.8694 - val_loss: 0.3499 - val_accuracy: 0.8498
Epoch 86/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3398 - accuracy: 0.8538 - val_loss: 0.3531 - val_accuracy: 0.8529
Epoch 87/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3154 - accuracy: 0.8730 - val_loss: 0.3444 - val_accuracy: 0.8511
Epoch 88/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3348 - accuracy: 0.8647 - val_loss: 0.3475 - val_accuracy: 0.8503
Epoch 89/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3240 - accuracy: 0.8725 - val_loss: 0.3447 - val_accuracy: 0.8542
Epoch 90/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3188 - accuracy: 0.8700 - val_loss: 0.3445 - val_accuracy: 0.8529
Epoch 91/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3249 - accuracy: 0.8714 - val_loss: 0.3472 - val_accuracy: 0.8503
Epoch 92/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3189 - accuracy: 0.8739 - val_loss: 0.3502 - val_accuracy: 0.8507
Epoch 93/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3323 - accuracy: 0.8705 - val_loss: 0.3441 - val_accuracy: 0.8529
Epoch 94/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3312 - accuracy: 0.8643 - val_loss: 0.3450 - val_accuracy: 0.8529
Epoch 95/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3375 - accuracy: 0.8620 - val_loss: 0.3455 - val_accuracy: 0.8516
Epoch 96/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3193 - accuracy: 0.8670 - val_loss: 0.3456 - val_accuracy: 0.8533
Epoch 97/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3368 - accuracy: 0.8635 - val_loss: 0.3481 - val_accuracy: 0.8524
Epoch 98/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3409 - accuracy: 0.8656 - val_loss: 0.3466 - val_accuracy: 0.8533
Epoch 99/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3285 - accuracy: 0.8680 - val_loss: 0.3467 - val_accuracy: 0.8520
Epoch 100/100
469/469 [==============================] - 1s 2ms/step - loss: 0.3492 - accuracy: 0.8585 - val_loss: 0.3464 - val_accuracy: 0.8537

In [44]:
#predicts for test_data
y_pred =classifer.predict(X_test)
y_pred =(y_pred>0.5)

In [45]:
from sklearn import metrics
print("Accuracy_Score :",metrics.accuracy_score(y_test,y_pred))
print('Classification_report :\n',metrics.classification_report(y_test,y_pred))
print('Confusion_matrix :\n',metrics.confusion_matrix(y_test,y_pred))

Accuracy_Score : 0.8506666666666667
Classification_report :
               precision    recall  f1-score   support

           0       0.87      0.96      0.91      2375
           1       0.73      0.45      0.56       625

    accuracy                           0.85      3000
   macro avg       0.80      0.70      0.73      3000
weighted avg       0.84      0.85      0.84      3000

Confusion_matrix :
 [[2271  104]
 [ 344  281]]